sudo: required
services:
  - docker

before_install:
  - docker build -t vzs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vzs/react-test npm test -- --coverage

after_success:
  - docker build -t vzsteenekamp/multi-client ./client
  - docker build -t vzsteenekamp/multi-nginx ./nginx
  - docker build -t vzsteenekamp/multi-server ./server
  - docker build -t vzsteenekamp/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vzsteenekamp/multi-client
  - docker push vzsteenekamp/multi-nginx
  - docker push vzsteenekamp/multi-server
  - docker push vzsteenekamp/multi-worker

deploy:
  provider: elasticbeanstalk;
  region: eu-west-2
  app: multi-docker
  anv: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-684809727627
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
